<?php

namespace AppBundle\Repository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends \Doctrine\ORM\EntityRepository
{
  public function findCommentByUser($id, $params=null){

    $query = $this->createQueryBuilder('c')
        ->select($params)
        ->where(" c.userId = :id")
        ->setParameter('id', $id)
        ->getQuery();
        return $query->getResult();
  }

  public function findLastCommentPerArticle($id){
    //COUNT(f.follower) as friendsCount"
    $query = $this->createQueryBuilder('c')
        ->select("c.id, c.comment, c.userId, u.name")
        ->leftJoin('AppBundle:Users', 'u', \Doctrine\ORM\Query\Expr\Join::WITH, 'c.userId = u.id')
        ->where(" c.articleId = :id")
        ->setParameter('id', $id)
        ->orderBy('c.id', "desc")
        ->setMaxResults(3)
        ->getQuery();
        return $query->getArrayResult();

  }
}
