# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

services:
    app.articles:
        class:     AppBundle\Service\Article
        arguments: [ @doctrine.orm.entity_manager, @Router, @request_stack ]
